- hosts: servers
  gather_facts: false
  tasks:
    - name: Assign Port
      set_fact:
        ansible_port: 10022

    - name: Add keys
      authorized_key:
        user: user
        key: '{{ item }}'
        state: present
      with_file:
        - <path_to_stored_keys>
        - <path_to_stored_keys>
        - <path_to_stored_keys>